# 由 platform/scripts/gen_op_catalog.py 生成；勿手改（--check 校验）。
# polars 版本锁基准：1.44.1（dir(pl.Expr) 公开名 223 个）
from factorlab.core.ops.classification import Catalog, OpMeta

EL_METHODS = frozenset({
    'abs',
    'add',
    'alias',
    'and_',
    'arccos',
    'arccosh',
    'arcsin',
    'arcsinh',
    'arctan',
    'arctanh',
    'arr',
    'bin',
    'bitwise_and',
    'bitwise_count_ones',
    'bitwise_count_zeros',
    'bitwise_leading_ones',
    'bitwise_leading_zeros',
    'bitwise_or',
    'bitwise_trailing_ones',
    'bitwise_trailing_zeros',
    'bitwise_xor',
    'cast',
    'cat',
    'cbrt',
    'ceil',
    'clip',
    'cos',
    'cosh',
    'cot',
    'degrees',
    'dot',
    'dt',
    'eq',
    'eq_missing',
    'exp',
    'ext',
    'fill_nan',
    'fill_null',
    'floor',
    'floordiv',
    'ge',
    'gt',
    'is_between',
    'is_close',
    'is_finite',
    'is_in',
    'is_infinite',
    'is_nan',
    'is_not_nan',
    'is_not_null',
    'is_null',
    'le',
    'least_squares',
    'list',
    'log',
    'log10',
    'log1p',
    'lt',
    'meta',
    'mod',
    'mul',
    'name',
    'ne',
    'ne_missing',
    'neg',
    'not_',
    'or_',
    'pow',
    'radians',
    'reinterpret',
    'replace',
    'replace_strict',
    'round',
    'round_sig_figs',
    'sign',
    'sin',
    'sinh',
    'sqrt',
    'str',
    'struct',
    'sub',
    'tan',
    'tanh',
    'to_physical',
    'truediv',
    'truncate',
    'where',
    'xor',
})

TS_METHODS = frozenset({
    'cum_count',
    'cum_max',
    'cum_min',
    'cum_prod',
    'cum_sum',
    'cumulative_eval',
    'diff',
    'ewm_mean',
    'ewm_mean_by',
    'ewm_std',
    'ewm_sum',
    'ewm_sum_by',
    'ewm_var',
    'forward_fill',
    'pct_change',
    'peak_max',
    'peak_min',
    'rolling_kurtosis',
    'rolling_map',
    'rolling_max',
    'rolling_max_by',
    'rolling_mean',
    'rolling_mean_by',
    'rolling_median',
    'rolling_median_by',
    'rolling_min',
    'rolling_min_by',
    'rolling_quantile',
    'rolling_quantile_by',
    'rolling_rank',
    'rolling_rank_by',
    'rolling_skew',
    'rolling_std',
    'rolling_std_by',
    'rolling_sum',
    'rolling_sum_by',
    'rolling_var',
    'rolling_var_by',
    'shift',
})

TS_WINDOWS = {
    'cum_count': 'unbounded',
    'cum_max': 'unbounded',
    'cum_min': 'unbounded',
    'cum_prod': 'unbounded',
    'cum_sum': 'unbounded',
    'cumulative_eval': 'unbounded',
    'diff': 'arg:0',
    'ewm_mean': 'unbounded',
    'ewm_mean_by': 'unbounded',
    'ewm_std': 'unbounded',
    'ewm_sum': 'unbounded',
    'ewm_sum_by': 'unbounded',
    'ewm_var': 'unbounded',
    'forward_fill': 'unbounded',
    'pct_change': 'arg:0',
    'peak_max': 'unbounded',
    'peak_min': 'unbounded',
    'rolling_kurtosis': 'arg:0',
    'rolling_map': 'arg:0',
    'rolling_max': 'arg:0',
    'rolling_max_by': 'arg:1',
    'rolling_mean': 'arg:0',
    'rolling_mean_by': 'arg:1',
    'rolling_median': 'arg:0',
    'rolling_median_by': 'arg:1',
    'rolling_min': 'arg:0',
    'rolling_min_by': 'arg:1',
    'rolling_quantile': 'arg:0',
    'rolling_quantile_by': 'arg:1',
    'rolling_rank': 'arg:0',
    'rolling_rank_by': 'arg:1',
    'rolling_skew': 'arg:0',
    'rolling_std': 'arg:0',
    'rolling_std_by': 'arg:1',
    'rolling_sum': 'arg:0',
    'rolling_sum_by': 'arg:1',
    'rolling_var': 'arg:0',
    'rolling_var_by': 'arg:1',
    'shift': 'arg:0',
}

DENIED_METHODS = frozenset({
    'agg_groups',
    'all',
    'any',
    'append',
    'approx_n_unique',
    'arg_max',
    'arg_min',
    'arg_sort',
    'arg_true',
    'arg_unique',
    'backward_fill',
    'bottom_k',
    'bottom_k_by',
    'count',
    'cut',
    'deserialize',
    'drop_nans',
    'drop_nulls',
    'entropy',
    'exclude',
    'explode',
    'extend_constant',
    'filter',
    'first',
    'flatten',
    'from_json',
    'gather',
    'gather_every',
    'get',
    'has_nulls',
    'hash',
    'head',
    'hist',
    'implode',
    'index_of',
    'inspect',
    'interpolate',
    'interpolate_by',
    'is_duplicated',
    'is_empty',
    'is_first_distinct',
    'is_last_distinct',
    'is_sorted',
    'is_unique',
    'item',
    'kurtosis',
    'last',
    'len',
    'limit',
    'lower_bound',
    'map_batches',
    'map_elements',
    'max',
    'max_by',
    'mean',
    'median',
    'min',
    'min_by',
    'mode',
    'n_unique',
    'nan_max',
    'nan_min',
    'null_count',
    'over',
    'pipe',
    'product',
    'qcut',
    'quantile',
    'rank',
    'rechunk',
    'register_plugin',
    'repeat_by',
    'reshape',
    'reverse',
    'rle',
    'rle_id',
    'rolling',
    'sample',
    'search_sorted',
    'set_sorted',
    'shrink_dtype',
    'shuffle',
    'skew',
    'slice',
    'sort',
    'sort_by',
    'std',
    'sum',
    'tail',
    'top_k',
    'top_k_by',
    'unique',
    'unique_counts',
    'upper_bound',
    'value_counts',
    'var',
})

DENIED_GUIDANCE = {
    'agg_groups': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'all': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'any': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'append': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'approx_n_unique': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'arg_max': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'arg_min': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'arg_sort': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'arg_true': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'arg_unique': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'backward_fill': '用未来值回填（未来函数）',
    'bottom_k': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'bottom_k_by': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'count': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'cut': '改用 Plan 3 的 cut 原语（显式分组语义）',
    'deserialize': '反序列化不是因子计算算子',
    'drop_nans': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'drop_nulls': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'entropy': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'exclude': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'explode': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'extend_constant': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'filter': '分组过滤语义不明确；请在池公式/universe 中表达',
    'first': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'flatten': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'from_json': '解析 JSON 不是因子计算算子',
    'gather': '行选择会跨资产/跨时间取值，语义不明确',
    'gather_every': '行选择会跨资产/跨时间取值，语义不明确',
    'get': '按下标取值（跨资产/跨时间），语义不明确',
    'has_nulls': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'hash': '哈希不是因子计算算子',
    'head': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'hist': '直方图是绘图命名空间',
    'implode': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'index_of': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'inspect': '调试输出不是因子计算算子',
    'interpolate': '插值使用未来已知点（未来函数）',
    'interpolate_by': '插值使用未来已知点（未来函数）',
    'is_duplicated': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'is_empty': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'is_first_distinct': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'is_last_distinct': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'is_sorted': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'is_unique': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'item': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'kurtosis': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'last': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'len': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'limit': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'lower_bound': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'map_batches': '任意 Python 回调不可静态验证（含未来函数风险）',
    'map_elements': '任意 Python 回调不可静态验证（含未来函数风险）',
    'max': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'max_by': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'mean': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'median': '改用语义明确的 cs_/gp_ 算子或显式分组（Plan 3 by=）',
    'min': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'min_by': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'mode': '改用语义明确的 cs_/gp_ 算子或显式分组（Plan 3 by=）',
    'n_unique': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'nan_max': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'nan_min': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'null_count': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'over': '改用语义明确的 cs_/gp_ 算子或显式分组（Plan 3 by=）',
    'pipe': '任意 Python 回调不可静态验证（含未来函数风险）',
    'product': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'qcut': '改用 Plan 3 的 cut 原语（显式分组语义）',
    'quantile': '改用语义明确的 cs_/gp_ 算子或显式分组（Plan 3 by=）',
    'rank': '改用语义明确的 cs_/gp_ 算子或显式分组（Plan 3 by=）',
    'rechunk': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'register_plugin': '注册外部插件不在公式层开放面内',
    'repeat_by': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'reshape': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'reverse': '反转序列 = 取未来值（未来函数）',
    'rle': '游程编码依赖全序列状态，语义不明确',
    'rle_id': '游程编号依赖全序列状态，语义不明确',
    'rolling': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'sample': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'search_sorted': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'set_sorted': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'shrink_dtype': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'shuffle': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'skew': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'slice': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'sort': '排序/选行语义不明确；时序请用 shift/diff/rolling_*',
    'sort_by': '排序/选行语义不明确；时序请用 shift/diff/rolling_*',
    'std': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'sum': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'tail': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'top_k': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'top_k_by': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'unique': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'unique_counts': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'upper_bound': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'value_counts': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
    'var': '该方法语义取决于上下文（分组/排序/聚合），Plan 1 不开放；请改用 cs_/gp_ 算子或 Plan 3 的 by= 分组',
}


def build_polars_catalog(catalog: Catalog) -> None:
    for name in EL_METHODS:
        catalog.add(OpMeta(f".{name}", "el", None, (), "polars_method", f".{name}"), replace=True)
    for name in TS_METHODS:
        catalog.add(OpMeta(f".{name}", "ts", TS_WINDOWS[name], (), "polars_method", f".{name}"), replace=True)
